### ISSUE TITLE
Discussion: API Design commands vs. flags

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-cli#14]
>  I would like to use this issue to discuss the final design. cc: @etiennedi 

If we're discussing design I'd also like to mention something that is technically off-topic to this suggestion, but would also affect the final design here.

Currently, the `cli` tool uses flags for everything, however, some flags should in my opinion actually be commands. For example, `weaviate-cli --init --init-email foo@bar.com` uses `--init` as a command (i.e. tells the CLI to run the init process) and uses `--init-email` for config option (i.e. tells the CLI what the email is).

A more typical API would be in my opinion be something like `weaviate-cli init --email foo@bar.com`, whereas `init` would be a command, and `--email` a config flag that is scoped only to the init command. Commands can of course also be hierarchical, so for this issues we'd end up with (`weaviate-cli sandbox create` and `weaviate-cli sandbox create --current`)

A major benefit is that the commands are their own scopes which can also have their own help menus. For example `weaviate-cli --help` would print a generic help whereas `weaviate-cli sandbox --help` would print a sandbox-specific help.

This is a pattern that is quite common. For example If you want to retrieve the credentials from a GKE cluster with the `gcloud` tool, you would run `gcloud container clusters get-credentials --zone europe-west1-b`, whereas `container` is the first hierarchical command, `clusters` is the second and `get-credentials` the third. Finally, `--zone=europe-west1-b` is additional config option via a flag.

Now that I've written this, I realize even more how much of it's own topic this should be and I recommend creating a new issues based off of this comment. Nevertheless it would affect this design as well.

_Originally posted by @etiennedi in https://github.com/semi-technologies/weaviate-cli/issues/13#issuecomment-507710430_

**Comment by bobvanluijt** [comment]
Any thoughts @fefi42?

**Comment by fefi42** [comment]
From a usability perspective this is the better solution, since it follows the most typically seen approach. I am all for it.

**Comment by bobvanluijt** [comment]
Wonderful, let’s go for it 💪

**Comment by fefi42** [comment]
I would suggest the following commands:

```
weaviate-cli schema import [--overwrite] [argument file]
weaviate-cli schema export 
weaviate-cli schema truncate

weaviate-cli concept import [--excel, --json] [argument file]
weaviate-cli concept empty [--force]

weaviate-cli config set [--url, --email, --auth, --init (manually querry all)] or [argument file]
weaviate-cli config view

weaviate-cli sandbox create [--email, --async, --no-default, --replace]
weaviate-cli sandbox delete [--async, --no-default]

weaviate-cli ping
weaviate-cli [--version]
```

**Comment by etiennedi** [comment]
@fefi42 This looks really well-designed. I'm not familiar with the current functionality of the cli, so I can't confirm or deny that all current functionality is accurately reflected in the above. But the structure makes sense.

Side-Note: @bobvanluijt and I had a talk about coming up with a glossary of all the terms we used. We released that `concepts` is one of the terms we use too often with ambigious meaning. @bobvanluijt is the updated list already present somewhere? I think in the latest version we called the individual instance of a class, (e.g. `{"class": "City", "schema": { "name": "Amsterdam"} }` a `Class Object`. 

So reflecting this, the commands
```
weaviate-cli concept import [--excel, --json] [argument file]
weaviate-cli concept empty [--force]
```

should probably be called `weaviate-cli object(s)` or `weaviate-cli classobject(s)`?

**Comment by fefi42** [comment]
I think that is a good idea. I even thought about just calling it data, since this would give an intuitive understanding even for somebody who never read any docs. But I also like object since it is a metaphor known from OOP.

**Comment by bobvanluijt** [comment]
> @bobvanluijt is the updated list already present somewhere?

Nope, not yet, but it is on my todo.

**Comment by bobvanluijt** [comment]
This looks a lot like the current setup. Currently, we go only one deep with commands namely;

```
    init                Initiate a Weaviate. This function is used to connect
                        the CLI to a Weaviate instance
    schema-import       The schema file should be in the same format as
                        the/weaviate/v1/schema RESTful output
    schema-export       Save a copy of the Weaviate's schema to disk
    schema-truncate     Truncate the schema, the Weaviate must be empty.
    empty               Empty the Weaviate (i.e., all concepts will be
                        removed)
    sandbox-create      Create a Weaviate sandbox on the SeMI network
    sandbox-remove      Delete a sandbox
    ping                Validate if a Weaviate can be pinged with or without
                        authentication
    version             Get the current version number
```

The reason we have `schema-export` instead of `schema export` is because the library used to create the arguments doesn't eat multiple sub args (I might be wrong, maybe there is a workaround? Or maybe it didn't search well enough) based on this I would propose to go for:

```
    config-set          Initiate a Weaviate. This function is used to connect
                        the CLI to a Weaviate instance
    config-view         View a config
    schema-import       The schema file should be in the same format as
                        the/weaviate/v1/schema RESTful output
    schema-export       Save a copy of the Weaviate's schema to disk
    schema-truncate     Truncate the schema, the Weaviate must be empty.
    classobjects-import Import into the Weaviate
    classobjects-empty  Empty the Weaviate (i.e., all concepts will be
                        removed)
    sandbox-create      Create a Weaviate sandbox on the SeMI network
    sandbox-remove      Delete a sandbox
    ping                Validate if a Weaviate can be pinged with or without
                        authentication
    version             Get the current version number
```

**Comment by fefi42** [comment]
The API uses the command group pattern utilizing the [click](https://click.palletsprojects.com/en/7.x/) module.
