### ISSUE TITLE
Parse Excel/CSV to ontology

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-cli#16]
Goal: Import an ontology described by csv files.

Different files are describing the things and properties. The parser should import the data scheme (from meta information file name and columns) into weaviate if it does not yet exist. It should also fill the database with all the concepts described by the table rows.

@bobvanluijt

**Comment by bobvanluijt** [comment]
First of all, this one has low priority for me _unless_ @michaverhagen needs this urgently.

## requirements

_note, the title says Excel/CSV but it should only be Excel for the concept will not work on CSV_

1. Every tab in a workbook represents a weaviate-class.
2. Every column represents a weaviate-property.
3. Every cell the value of a weaviate property.
4. A cell can contain `$[thing][ID]` or an Excel reference which should be resolved when adding the data to a Weaviate.

**Comment by bobvanluijt** [comment]
@michaverhagen, can you please attach a simple example for @fefi42?

**Comment by fefi42** [comment]
I am closing for now feel free to reopen if this needs priority.
